workflows:
  ios:
    name: iOS build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Fetching Dependencies
        script: |
          flutter packages get
      - name: Build iOS App
        script: |
          flutter build ios --no-codesign --release
    artifacts:
      - build/ios/iphoneos/Runner.app
    publishing:
      email:
        recipients:
          - senchabrest@gmail.com
