workflows:
  ios:
    name: iOS build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up keychain
        script: |
          security create-keychain -p "" build.keychain
          security list-keychains -d user -s build.keychain
          security unlock-keychain -p "" build.keychain
      - name: Fetching Dependencies
        script: |
          flutter packages get
      - name: Build iOS App
        script: |
          set -e
          flutter build ios --no-codesign
      - name: Create .ipa
        script: |
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
          -archivePath build/ios/archive/Runner.xcarchive \
          -exportPath build/ios/ipa \
          -exportOptionsPlist <(echo '<?xml version="1.0" encoding="UTF-8"?><plist version="1.0"><dict><key>method</key><string>ad-hoc</string><key>compileBitcode</key><false/></dict></plist>') \
          CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - senchabrest@gmail.com
