workflows:
  ios:
    name: iOS build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up keychain
        script: |
          security create-keychain -p "" build.keychain
          security list-keychains -d user -s build.keychain
          security unlock-keychain -p "" build.keychain
      - name: Fetching Dependencies
        script: |
          flutter packages get
      - name: Build iOS App
        script: |
          set -e
          flutter build ios --no-codesign
      - name: Package .app into .ipa
        script: |
          mkdir -p build/ios/ipa
          xcrun -sdk iphoneos PackageApplication -v build/ios/iphoneos/Runner.app -o $PWD/build/ios/ipa/Runner.ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - senchabrest@gmail.com
