workflows:
  ios:
    name: iOS Build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod init || true
          pod install --repo-update

      - name: Install Flutter dependencies
        script: |
          flutter packages get

      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa

    publishing:
      email:
        recipients:
          - senchabrest@gmail.com
