workflows:
  ios:
    name: iOS build
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Set up keychain
        script: |
          security create-keychain -p "" build.keychain
          security list-keychains -d user -s build.keychain
          security unlock-keychain -p "" build.keychain
      - name: Fetching Dependencies
        script: |
          flutter packages get
      - name: Build iOS App
        script: |
          set -e
          flutter build ios --no-codesign
      - name: Create exportOptions.plist
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>ad-hoc</string>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF
      - name: Create .ipa
        script: |
          mkdir -p build/ios/ipa
          xcodebuild -exportArchive \
          -archivePath build/ios/archive/Runner.xcarchive \
          -exportPath build/ios/ipa \
          -exportOptionsPlist exportOptions.plist \
          CODE_SIGNING_ALLOWED=NO
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - senchabrest@gmail.com
